# These are the NGS barcodes used to label each SIMD||DNA
# computational product within the NGS run

# These barcodes are the 11-2 set from Hawkins et al. 
# Indel-correcting DNA barcodes for high-throughput sequencing
# https://github.com/hawkjo/freebarcodes

# These variables get loaded as a module in NGSanalysis.py

NGSBarcodes = [\
"AACAACAACAC", "AACAACGGTGG", "AACACCTTCTT", "AACATTGAGCC", \
"AACCGAGAAGT", "AACCGTCCACC", "AAGAAGCTCCG", "AAGACCATAGG", \
"AAGCGGTTATA", "AAGGTACTGAA", "AAGTTCATTCC", "AATAGTGTCGG", \
"AATTCCGCGCT", "ACAATGCGAAT", "ACCACAGATTA", "ACCGCTATGCC", \
"ACCTCCTGTAA", "ACGATGTTGTG", "ACGGAACCAGC", "ACGTAGGATAA", \
"ACTATTACTCC", "AGAAGAAGAGA", "AGCATCTCAAT", "AGCTCGGACCT", \
"AGGTGAGTCTT", "AGTCTAGCGTT", "AGTGCGCCAAC", "ATGGAGGACGG", \
"ATTAACATGCC", "ATTGGTGCATA", "CAAGCCTGTGG", "CAATCTTACAG", \
"CACGCATAACG", "CACTGGTTCCG", "CAGTAATTGGA", "CATACGACCGC", \
"CCAGAGCACAC", "CCAGGAGGTGT", "CCATTCGCTAG", "CCGCGTCTTAG", \
"CCTAACAAGTA", "CCTTATGGTCA", "CGAGACTATTC", "CGCCAAGCTGA", \
"CGGAGTCGAAC", "CGTACCTCTCC", "CGTGCCAGGAA", "CGTTAATACAC", \
"CTCCGATTCAA", "CTCTCGCGGAA", "CTTGACGTTAA", "GACCTGACATC", \
"GAGGATTGCCA", "GAGTGCGTGGT", "GATAAGCCTAA", "GCCGGTTGGAA", \
"GCCTTCTACGA", "GCGAATTAAGG", "GGACACCGTAA", "GGTATAGATGG", \
"GGTGTCCGCTT", "GTACTTGTTAG", "GTCGTCATGTC", "GTTACGGAGAG", \
"TAAGCTGCAAG", "TATCCAACTCC", "TCGCCTCCATC", "TCTGAGTAGCC", \
"TGAATGATACC", "TGGATCTGGTC", "TTAGAATCACG", "TTATCTCTTGC", \
"TTCAGGTGTTC", "TTCCTATGAGA", "TTCTGCACCGC"]